allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  better-sqlite3: true
  core-js: set this to true or false
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
